### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by ickeep** [mscdex/node-ftp#106]
Chinese garbled
Please solve
Thank！

{"type":"d","name":"è¿ä¸ªç®å½ç¨æ¥æ¾å¾çå§","sticky":false,"rights":{"user":"rwx","group":"rx","other":"rx"}

**Comment by yft** [comment]
try
```js
c.on('ready', function () {
  c.list(function (err, list) {
    if (err) throw err
    list.map(item => {
      item.name = Buffer.from(item.name, 'binary').toString('utf8')
    })
    console.dir(list)
    c.end()
  })
})
```

**Comment by bigtotorouk** [comment]
> 

so what should i do when uploading files

**Comment by bigtotorouk** [comment]
> try
> 
> ```js
> c.on('ready', function () {
>   c.list(function (err, list) {
>     if (err) throw err
>     list.map(item => {
>       item.name = Buffer.from(item.name, 'binary').toString('utf8')
>     })
>     console.dir(list)
>     c.end()
>   })
> })
> ```

so what should i do when uploading files
