### ISSUE TITLE
Ready never called, user not logged in?

### ISSUE THREAD

**Issue by ganna-shmatova** [mscdex/node-ftp#121]
Not quite sure what's going on here

I'm trying to get SFTP to work.

```js
var c = new ftp();
c.on('error', function(err){
	console.log(err);
});
c.on('greeting', function(msg){
	console.log(msg);
});
c.on('close', function(){
	console.log('closed');
});
c.on('end', function(){
	console.log('ended');
});
c.on('ready', function(){
	console.log('ready');
	c.list(function(err, list){
		console.log('listing');
		if(err) return cb(err);
		console.log(list);
		c.end();
	});
});
var key = fs.readFileSync('./ftp-key').toString();
console.log(key);
c.connect({
	host: '127.0.0.1',
	port: 22,
	user: 'ganna',
	password: 'password',
	secure: true,
	secureOptions: {
		rejectUnauthorized: false,
		pfx: key,
		// key: key,
		// cert: key,
		// ca: key,
	}
});
```

output: 
![image](https://cloud.githubusercontent.com/assets/7226694/8059302/3852025a-0e8d-11e5-8f33-e2daf979066c.png)

the ftp server is on my local machine (using filezilla). I can see someone not logged in connect. Then they time out after enough time. Why does this not log in?

'ready' is also never called. No errors ever displayed...

**Comment by mscdex** [comment]
Are you sure you're not confusing FTPS with SFTP (port 22)? They are two separate protocols. FTPS is just FTP over SSL/TLS, whereas SFTP is a totally different protocol over SSH. The only thing they share in common are the 3 letters :-)

If you do need SFTP, there's [`ssh2`](https://github.com/mscdex/ssh2) which does both SSH and SFTP.

**Comment by ganna-shmatova** [comment]
after enough finicking around i got ssh2 to work with the private key.

However, I am getting the exact same issue. Ready is never called, looks like client never tried logging in. https://github.com/mscdex/ssh2/issues/280

**Comment by mscdex** [comment]
Ok, so perhaps it's not SSH either. Can you share what your server settings are?

**Comment by ganna-shmatova** [comment]
Eventually I am looking to support all. FTP, TLS & FTP, SSH & FTP.

I have an actual server that I've PuTTy'ed in through SFTP and a .ppk file, however ssh2 says `malformed private key (expected sequence)` when I use the .ppk & connect to that server...

---

I thought it would be easier to try to setup a local server first & go from there...

local server configs:
![image](https://cloud.githubusercontent.com/assets/7226694/8062877/28b75152-0ea0-11e5-9547-dee9634244c2.png)
(uses same files as the client is trying to use)

1 user:
![image](https://cloud.githubusercontent.com/assets/7226694/8062907/5591dcec-0ea0-11e5-89e0-20f7042b6437.png)
with setup home folder:
![image](https://cloud.githubusercontent.com/assets/7226694/8062917/5daa3546-0ea0-11e5-8742-84aeee32db23.png)

**Comment by mscdex** [comment]
Ok, so it definitely is FTPS then, not SFTP. Can you set `debug: console.log` in your connection config object and post the output (censoring sensitive information)?

**Comment by mscdex** [comment]
Also, if you're using port 22 as you've set up in the server, that's for *implicit* SSL/TLS connections, so make sure you use `secure: 'implicit'` in your connection config. Otherwise use `port: 21` and `secure: true` to use explicit SSL/TLS.

**Comment by ganna-shmatova** [comment]
ok, with `secure: 'implicit'`
![image](https://cloud.githubusercontent.com/assets/7226694/8064616/ffb76558-0ea9-11e5-8537-877f4ad6abba.png)

with `port: 21` & `secure: true` (hey it got the greeting!)
![image](https://cloud.githubusercontent.com/assets/7226694/8064672/202a8446-0eaa-11e5-9c29-70e5176d3147.png)

**Comment by ganna-shmatova** [comment]
ok switched the key to `key` from `pfx`. Worked. Thanks a lot!
