### ISSUE TITLE
get function might not work properly.

### ISSUE THREAD

**Issue by tkang007** [mscdex/node-ftp#122]
When I use ftp.get as below, the final trailing data was not provided.
                 ftp.get(remotefile, function(err, rs) {
                        if (err) {
                            ...
                        }
                        rs.on('error', function(err) {
                            ...
                        });
                       rs.once('end', function() {
                            ...
                        });
                        rs.once('close', function(err) {
                            if (err) {
                               ...
                           }
                        });
                        rs.pipe(cleancount).pipe(psql.stdin);   // trailing part not arrived.
                  });
ftp server side may close the socket after sending whole file content,
ftp client side may not feed the traling data on finish and close event.  

Is there any way to control this issue?
Thanks in advance,
Taewon

**Comment by mscdex** [comment]
Can you try the master branch and let me know if that helps things at all?

**Comment by tkang007** [comment]
Same case was happened with Master. 
This case was happened with ftpdmin and sfk at Windows 7.
If you have any simple test case for this issue, I would like to test with it.

**Comment by tkang007** [comment]
This case might be related with child_process stdio issue. https://github.com/joyent/node/issues/3737

**Comment by mscdex** [comment]
So does the problem happen for any file that you download from the ftpdmin server using this module?
