### ISSUE TITLE
if utf8 filename

### ISSUE THREAD

**Issue by yanmingsohu** [mscdex/node-ftp#124]
modify 434: var sockerr, done = false, replies = 0, entries, buffer = [], source = sock;
modify 441: source.on('data', function(chunk) { buffer.push(chunk); });
insert   455: buffer = Buffer.concat(buffer).toString();

**Comment by AyrA** [comment]
This did not fix the problem for me. When I retrieve a directory listing on my server, chars like äöü are messed up. They seem to be encoded twice. I have tried the ascii option but this does not helps.

It looks like data over a PASV connection is always treated as binary, but some commands, like CWD,PWD and LIST should be treated as UTF-8 text. Modern FTP Servers (for example FileZilla Server) have UTF-8 always on and it cannot be turned off (OPTS utf8 OFF)

**Comment by mscdex** [comment]
I'd be open to a PR that checks for the UTF-8 feature (enabling it if possible) and then using UTF-8 encoding for non-file transfers if said feature is available. The `binary` usage was originally there because some servers were using other encodings and converting them to ascii/utf8 would cause the text to be mangled.

**Comment by AyrA** [comment]
@mscdex A server announces this feature in the FEAT command:

	FEAT
	211-Features:
	MDTM
	REST STREAM
	SIZE
	MODE Z
	MLST type*;size*;modify*;
	MLSD
	AUTH SSL
	AUTH TLS
	PROT
	PBSZ
	UTF8 <-- This
	CLNT
	MFMT
	211 End

**Comment by AyrA** [comment]
The solution from @yanmingsohu has worked in the end. I was piping the output directly to the http component (to make a http frontend for ftp if somebody is interested) where it got mangled. I will make a PR addressing this.

**Comment by AyrA** [comment]
I just did: https://github.com/mscdex/node-ftp/pull/125

This will prevent double escaping of UTF-8. If the server operates in true ascii mode this should not mess up as well, as ascii is only the lower 127 bytes and UTF-8 is identical in this case.
