### ISSUE TITLE
mkdir if directory not exists?

### ISSUE THREAD

**Issue by fr-kshibata** [mscdex/node-ftp#128]
How do you Implement mkdir if directory does not exists? 
I tried using fs like this

c.on('ready', function() {
    if (!fs.existsSync(REMOTE_DIRECTORY)){
       fs.mkdir(REMOTE_DIRECTORY);}
    c.put(LOCAL_FILE,REMOTE_DIRECTORY+REMOTE_FILE, function(err) {
      if (err) throw err;
      console.log('successfully uploaded file');
      c.end();
    });
  });

probably i cannot do it like this because it is already connected to the ftp 
Can you make a function that mkdir if not exists?
Please :)

Thanks Brian!

**Comment by mscdex** [comment]
There's already a [`mkdir()`](https://github.com/mscdex/node-ftp#optional-standard-commands-rfc-959) command, provided the server supports it.

**Comment by fr-kshibata** [comment]
Yes but how do you implement mkdir() if the dir does not exists?

**Comment by mscdex** [comment]
I'm afraid I don't understand what the problem is. Are you asking about recursively making a directory on the remote side, like `mkdir -p` does, or something else?

**Comment by fr-kshibata** [comment]
Yes something like mkdir -p but it should not make a directory if it already exists and should log that the directory exists. Is it possible to do that?

**Comment by fr-kshibata** [comment]
I g
