### ISSUE TITLE
FTPS support

### ISSUE THREAD

**Issue by marcandrews** [mscdex/node-ftp#132]
Is FTPS support available and if not, can it be added?

**Comment by mscdex** [comment]
Yes, FTPS support already exists. SFTP support however, requires a different module (e.g. `ssh2`).

**Comment by marcandrews** [comment]
Thanks!

**Comment by aredfox** [comment]
I would like to add that the options "secureOptions" isn't documented very well. I don't know the internals of it or what parameters we can pass to it, can that be expanded? See also ref issue https://github.com/mscdex/node-ftp/issues/153

**Comment by aredfox** [comment]
ok, sorry, found it: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback
