### ISSUE TITLE
get() several files in parallel

### ISSUE THREAD

**Issue by flesler** [mscdex/node-ftp#134]
Hi, I noticed that when calling get() several times it seems to queue downloads and won't start one until the previous ended.

Is there any way around this?

Thanks

**Comment by mscdex** [comment]
Not without opening separate connections, no. That's just how FTP works.

**Comment by flesler** [comment]
Oh right, I could open several connections.
Thanks!

**Comment by sudhir-pandey24** [comment]
@flesler Can you write full queue process code here. I have stuck on same problem

**Comment by flesler** [comment]
@sudhir-pandey24 this was 7 years ago, don't have that code anymore

**Comment by sudhir-pandey24** [comment]
This is my code sample. Can you help me to resolve @flesler 
   
             var downloadList = [];
            var allFileNames = [];

           const ftpConnection = async (callback) => {
	       try{
		     ftp_client.on('ready', function() { 
			   ftp_client.list('/Gracenote',function(err, list) {
				  list.map(function(entry){
					if (entry.name !== '.' && entry.name !== '..') {
						downloadList.push(entry.name);
					}
				    });	
				    callback(downloadList);
				    ftp_client.end();
			      });
		           });
	             } catch (error) {
		            console.log(error);
	             }
                 }

            ftpConnection(function(a) {
	              allFileNames = a;
	               // Defining the queue
	              const queue = asyncProccess.queue((task, completed) => {
	              // Simulating a Complex task
	              setTimeout(()=>{
		            // The number of tasks to be processed
		          const remaining = queue.length();
		         completed(null, {task, remaining});
		  
		      ftp_client.get(`Gracenote/${task}`, function(err, stream) {
			  if (err) console.dir(err);
			  if(!err){
					console.log(`copied file Gracenote/${task}`);
					stream.once('close', function() { ftp_client.end(); });
					stream.pipe(fs.createWriteStream('data/'+ task,{flags: 'w'}));
			        }
			     });
	              }, 1000);

	            }, 2); // The concurrency value is 1
	
	        // Adding the each task to the queue
	         allFileNames.forEach((task)=>{
		 
		  // Adding the 5th task to the head of the
		  // queue as it is deemed important by us
		  if(task == 5){
		  queue.unshift(task, (error, {task, remaining})=>{
			if(error){
			 console.log(`An error occurred while processing task ${task}`);
			}else {
			 console.log(`Finished processing task ${task}. ${remaining} tasks remaining`);
			}
		  })     
			  // Adding the task to the tail in the order of their appearance
		} else {
			queue.push(task, (error, {task, remaining})=>{
			 if(error){
			  console.log(`An error occurred while processing task ${task}`);
			 }else {
			  console.log(`Finished processing task ${task}. ${remaining} tasks remaining`);
			}
			})
		  }
		});

		// Executes the callback when the queue is done processing all the tasks
		queue.drain(() => {
		  console.log('Successfully processed all items');
		})
	
              });


               const downloadXMLFile = async function (fileName) {
	         try{
		           ftp_client.on('ready', function() { 
			           ftp_client.get(`Gracenote/${fileName}`, function(err, stream) {
		                       if (err) console.dir(err);
		                       if(!err){
				            console.log(`copied file Gracenote/${fileName}`);
				            stream.once('close', function() { ftp_client.end(); });
				            stream.pipe(fs.createWriteStream('data/'+ fileName,{flags: 'w'}));
		                      }
		                 });
		            });	
	              }catch (err) {
		              return err.message;
	              }
                };
