### ISSUE TITLE
ignore expired certificate

### ISSUE THREAD

**Issue by jmarceli** [mscdex/node-ftp#136]
When connecting to my server I get: `Error: certificate has expired`. Is it possible to ignore this error and establish connection anyway?

**Comment by jmarceli** [comment]
For anyone having same problem. The solution is to define:
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`
Before connecting.

**Comment by mscdex** [comment]
A (better) way to do this non-globally is to use the `secureOptions` config option to pass options (e.g. `rejectUnauthorized: false`) directly to node's `tls.connect()`.

**Comment by jmarceli** [comment]
Thanks. My answer was just a quick fix.
