### ISSUE TITLE
Cannot connect using node-ftp - Handshake failed

### ISSUE THREAD

**Issue by developeron29** [mscdex/node-ftp#140]
After turning 
debug: console.log, 

I got the following consoles:
[connection] < 'SSH-2.0-WingFTPserver\r\n'
[connection] < '\u0000\u0000\u0000$\u0006\u0001\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0010Handshake failed\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'

Any help would be deeply appreciated, Thanks!

**Comment by mscdex** [comment]
The `ftp` module is for plain FTP and FTPS, it does not support SFTP, which requires SSH support. For SFTP support, you can use the [`ssh2`](https://github.com/mscdex/ssh2) module.
