### ISSUE TITLE
Version number in package.json is out of date

### ISSUE THREAD

**Issue by bachvtuan** [mscdex/node-ftp#150]
I get   [this issue](https://github.com/mscdex/node-ftp/pull/125), I see this is closed but I still get via npm install. I tried to download from github and it worked well.

I realize that current version is "0.3.10". It haven't updated for a year so  npm doesn't know the newer  code to pull.
Could you increase version number in package.json to solve ?

**Comment by sitexw** [comment]
+1
(@mscdex)

**Comment by bachvtuan** [comment]
This package seems is abandoned.
