### ISSUE TITLE
Can't receive  "greeting" events

### ISSUE THREAD

**Issue by fly2011** [mscdex/node-ftp#154]
all log  :
 [connection] < 'SSH-2.0-OpenSSH_6.6.1\r\n'

Established connection,Receives the data 'SSH-2.0-OpenSSH_6.6.1\r\n',but Unable to continue,

**Comment by mscdex** [comment]
That's ssh/sftp. This module is for plain ftp. For ssh/sftp, you will want the [`ssh2`](https://github.com/mscdex/ssh2) module.

**Comment by fly2011** [comment]
thanks
