### ISSUE TITLE
Is it possible that ftp.get(..) call the callback more than once?

### ISSUE THREAD

**Issue by konpatp** [mscdex/node-ftp#165]
I'm using node-ftp to retrieve a lot of files by creating many concurrent connections. 

I occasionally encountered a situation where ftp.get(..) call its callback more than once ! And I tried hard to be sure about this I counted the calls and turned out to be >= 1 but <= 2 !

I think the ftp confusingly call some other's callback resulting some to be called more than once ...

**Comment by zshaw-brightcove** [comment]
have you ever been able to reproduce that with debug on? I'm currently evaluating this library and this is a very heavy ftp.get application.

**Comment by konpatp** [comment]
i cant do it until now ... I ended up rewrite the way I use this lib and the problem just gone. Maybe uts my fault. I ll close this now
