### ISSUE TITLE
Multiple Concurrent Connections

### ISSUE THREAD

**Issue by alolis** [mscdex/node-ftp#18]
Hello,

I would like if this feature is supported by node-ftp. I went through documentation but i couldn't find anything. If not, is it going to?

Thank you for your time

**Comment by kenichi-shibata** [comment]
@mscdex I'm trying to do multiple 'put' operation in one connection can you show me an example how to this using generic-pool?

**Comment by mscdex** [comment]
@alolis You can't do multiple operations in parallel on a single connection. If you're using something like `generic-pool`, you're using multiple connections. I do not have any specific examples for using with `generic-pool` but it should be fairly straight forward if you follow their documentation.

**Comment by alolis** [comment]
@mscdex , wrong user :p You probably meant @fr-kshibata

**Comment by mscdex** [comment]
Ah yes, sorry.
