### ISSUE TITLE
Image Uploaded as an empty File

### ISSUE THREAD

**Issue by aiswarya4confianz** [mscdex/node-ftp#204]
When an image is uploaded, "one.jpg" an empty file is created. Below mentioned is my code.
`ftpClient.on('ready', function () {                          
          ftpClient.put("image.jpg", "one.jpg",false, function (err) {            
            if (err) {              
              throw err;
            }
            ftpClient.end();
          });
      });`
Thanks

**Comment by aiswarya4confianz** [comment]
Downloading to a temp file and then upload resolved my issue

**Comment by aiswarya4confianz** [comment]
Downloading to a temp file and then uploading to server resolved my issue

**Comment by GuilhermeHausz** [comment]
how you set the path location in your ftp?
