### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by atian25** [mscdex/node-ftp#22]
hi, I'm using node-ftp at win7 cmd (chinese, gbk), and got trouble at list file name.

here is a workaround only for test, could you plz add support to this issue?

<pre>
<code>
var iconv = require('../iconv-lite');
var BufferHelper = require('../bufferhelper');

FTP.prototype._pasvGetLines = function(emitter, type, cb) {
  return this.send('PASV', function(e, stream) {
    if (e)
      return cb(e);
    var curData = '', lines;

    //stream.setEncoding('utf8');
    
    stream.on('data', function(data) {

      var bufferHelper = new BufferHelper();
      bufferHelper.concat(data);

      curData += data;
      if (/\r\n|\n/.test(curData)) {

        curData = iconv.decode(bufferHelper.toBuffer(),'gbk');

        if (curData[curData.length-1] === '\n') {
          lines = curData.split(/\r\n|\n/);
          curData = '';
        } else {
          var pos = curData.lastIndexOf('\r\n');
          if (pos === -1)
            pos = curData.lastIndexOf('\n');
          lines = curData.substring(0, pos).split(/\r\n|\n/);
          curData = curData.substring(pos+1);
        }
        processDirLines(lines, emitter, type);
      }
    });
    stream.on('end', function() {
      emitter.emit('end');
    });
    stream.on('error', function(e) {
      emitter.emit('error', e);
    });
    cb();
  });
};
</code>
</pre>

**Comment by lizhipower** [comment]
i can get the file lists from the ftp, and with iconv.decode(list.name, 'gbk') I can get the correct Chinese, but the problem is how can I get the specified file lists of a folder in Chinese, like ‘/测试’
i can't the file lists with
 `ftpClient.list( ‘/测试’, (e, list1) => {
    if (e) throw e;
    console.log(list1);
  });`
but it;s ok with
 `ftpClient.list( ‘/test’, (e, list1) => {
    if (e) throw e;
    console.log(list1);
  });`

**Comment by lfcgomes** [comment]
@lizhipower any advance on this? How did you solve this? I'm facing the same issue here.

**Comment by lizhipower** [comment]
yeah use the raw ftp cmd

Get Outlook for iOS




On Mon, Oct 17, 2016 at 6:47 PM +0800, "Luís Gomes" <notifications@github.com> wrote:












@lizhipower any advance on this? How did you solve this? I'm facing the same issue here.

**Comment by likev** [comment]
@mscdex you should use Buffer with filepath, or add a encode option with method such as list, cwd etc.
```js
FTP.prototype.cwd = function (path, cb, promote) {
    let cmddata = 'CWD ';
    if (Buffer.isBuffer(path)) cmddata = Buffer.concat([Buffer.from(cmddata), path]);
     else cmddata += path;

    this._send(cmddata, function (err, text, code) {
        if (err)
        return cb(err);
        var m = RE_WD.exec(text);
        cb(undefined, m ? m[1] : undefined);
    }, promote);
};
FTP.prototype._send = function (cmd, cb, promote) {
    clearTimeout(this._keepalive);
    if (cmd !== undefined) {
        if (promote)
        this._queue.unshift({
            cmd: cmd,
            cb: cb
        });
         else
        this._queue.push({
            cmd: cmd,
            cb: cb
        });
    }
    var queueLen = this._queue.length;
    if (!this._curReq && queueLen && this._socket && this._socket.readable) {
        this._curReq = this._queue.shift();
        if (this._curReq.cmd === 'ABOR' && this._pasvSocket)
        this._pasvSocket.aborting = true;
        this._debug && this._debug('[connection] > ' + inspect(this._curReq.cmd));
        
        let cmddata = this._curReq.cmd;
        if (Buffer.isBuffer(cmddata)) cmddata = Buffer.concat([cmddata, Buffer.from('\r\n')]);
         else cmddata += '\r\n';
        this._socket.write(cmddata);
    } else if (!this._curReq && !queueLen && this._ending)
    this._reset();
};

```

**Comment by iamlion** [comment]
> i can get the file lists from the ftp, and with iconv.decode(list.name, 'gbk') I can get the correct Chinese, but the problem is how can I get the specified file lists of a folder in Chinese, like ‘/测试’
> i can't the file lists with
> `ftpClient.list( ‘/测试’, (e, list1) => { if (e) throw e; console.log(list1); });`
> but it;s ok with
> `ftpClient.list( ‘/test’, (e, list1) => { if (e) throw e; console.log(list1); });`

how to resolve it?

**Comment by iamlion** [comment]
> i can get the file lists from the ftp, and with iconv.decode(list.name, 'gbk') I can get the correct Chinese, but the problem is how can I get the specified file lists of a folder in Chinese, like ‘/测试’
> i can't the file lists with
> `ftpClient.list( ‘/测试’, (e, list1) => { if (e) throw e; console.log(list1); });`
> but it;s ok with
> `ftpClient.list( ‘/test’, (e, list1) => { if (e) throw e; console.log(list1); });`

I resolve it , You need convert 'cmd' to 'GBK'.

```
var iconv = require("../../iconv-lite");

FTP.prototype._send = function(cmd, cb, promote) {
  clearTimeout(this._keepalive);
  if (cmd !== undefined) {
    if (promote)
      this._queue.unshift({ cmd: cmd, cb: cb });
    else
      this._queue.push({ cmd: cmd, cb: cb });
  }
  var queueLen = this._queue.length;
  if (!this._curReq && queueLen && this._socket && this._socket.readable) {
    this._curReq = this._queue.shift();
    if (this._curReq.cmd === 'ABOR' && this._pasvSocket)
      this._pasvSocket.aborting = true;
    this._debug&&this._debug('[connection] > ' + inspect(this._curReq.cmd));

    let cmd = this._curReq.cmd + '\r\n';
    let buf = iconv.encode(cmd, 'gbk');
    this._socket.write(buf);
  } else if (!this._curReq && !queueLen && this._ending)
    this._reset();
};
```
