### ISSUE TITLE
mkdir at nested path

### ISSUE THREAD

**Issue by jescalan** [mscdex/node-ftp#27]
So here's my situation. I have one folder called 'stuff', which i create using the `mkdir` function like this, and it works great:

```
conn.mkdir('stuff', function(){ if (err){ throw err } });
```

Inside the stuff folder, I have another folder called 'more_stuff', which I attempt to create like this:

```
conn.mkdir('stuff/more_stuff', function(err){ if (err){ throw err } });
```

...unfortunately, this one throws me an error saying that 'stuff' already exists. Does this mean it's not possible to create a nested directory like this, and I need to `cd` into that directory first?

**Comment by kenichi-shibata** [comment]
Any updates for this?
