### ISSUE TITLE
Active mode ftp

### ISSUE THREAD

**Issue by futurechan** [mscdex/node-ftp#62]
Is active ftp supported (I know it is fairly unpopular)? I didn't see any documentation or an indication of that capability in the code, but maybe I missed it.

**Comment by sp00x** [comment]
Maybe it should be mentioned somewhere in the README that active mode is not supported, as that was a bit of a gotcha now as I was thinking "oh, this weird ftp server requires active mode, let's just set the uh.. hm.. where's the passive mode boolean value in the options.. where.. huh.. where.. oh.. it's nowhere"
