### ISSUE TITLE
226 Closing data connection

### ISSUE THREAD

**Issue by tuurleyck** [mscdex/node-ftp#90]
My ftp server is putting file transfers in 'Interrupted mode', because the data connection is closed without a QUIT command to logout the user first. The server performs the action of an abort as described in the RFC 959.

http://www.ietf.org/rfc/rfc959.txt

QUIT:
            This command terminates a USER and if file transfer is not
            in progress, the server closes the control connection.  If
            file transfer is in progress, the connection will remain
            open for result response and the server will then close it.
            If the user-process is transferring files for several USERs
            but does not wish to close and then reopen connections for
            each, then the REIN command should be used instead of QUIT.

```
        An unexpected close on the control connection will cause the
        server to take the effective action of an abort (ABOR) and a
        logout (QUIT).
```

**Comment by connor11528** [comment]
@mscdex is there any way to currently issue a QUIT command? @tuurleyck did you figure out a workaround to issue QUIT commands to the server?

**Comment by tuurleyck** [comment]
@connor11528 , the solution was the correct implementation of the 'logout' function.
This change was pulled long time ago and reflected in the README.md:

`logout(< function >callback) - (void) - Logout the user from the server. callback has 1 parameter: < Error >err.`

**Comment by connor11528** [comment]
Got it. Thanks @tuurleyck
